### ISSUE TITLE
/tick freeze doesn't work in 1.14.4

### ISSUE THREAD

**Issue by keikoutou** [DeadlyMC/QuickCarpet114#44]
I forgot to report in here. (same report as SciCraft Discord)

Minecraft Version : **1.14.4**

Mod Version : **quickcarpet-2.0.0-dev.20190913.130353**
(I can only find this mod version in SciCraft Discord)

```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 19/10/03 17:30
Description: Exception ticking world

java.lang.NoSuchMethodError: net.minecraft.class_3215.method_12127(Ljava/util/function/BooleanSupplier;)V
	at net.minecraft.class_3218.handler$tickFreeze$zcb000(class_3218.java:1588)
	at net.minecraft.class_3218.method_18765(class_3218.java)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:835)
	at net.minecraft.class_3176.method_3813(class_3176.java:343)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:774)
	at net.minecraft.server.MinecraftServer.handler$modifiedRunLoop$zbe000(MinecraftServer.java:2337)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:621)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_3218.handler$tickFreeze$zcb000(class_3218.java:1588)
	at net.minecraft.class_3218.method_18765(class_3218.java)

-- Affected level --
Details:
	All players: 1 total; [class_3222['keikoutou77'/118, l='world', x=219.83, y=87.68, z=-101.36]]
	Chunk stats: ServerChunkCache: 2115
	Level dimension: minecraft:overworld
	Level name: world
	Level seed: -1420145293045697276
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (240,78,-112), Chunk: (at 0,4,0 in 15,-7; contains blocks 240,0,-112 to 255,255,-97), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 953 game time, 953 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 110262 (now: false), thunder time: 39265 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:835)
	at net.minecraft.class_3176.method_3813(class_3176.java:343)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:774)
	at net.minecraft.server.MinecraftServer.handler$modifiedRunLoop$zbe000(MinecraftServer.java:2337)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:621)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_212, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 121475824 bytes (115 MB) / 660078592 bytes (629 MB) up to 954728448 bytes (910 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xms256M 

- [ ] -Xmx1G

	Player Count: 1 / 20; [class_3222['keikoutou77'/118, l='world', x=219.83, y=87.68, z=-101.36]]
	Data Packs: fabric/quickcarpet, fabric/minecraft, vanilla
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

```

**Comment by skyrising** [comment]
I can't reproduce the bug on my installation.
I tried fixing it though.
Can you try [this](https://github.com/DeadlyMC/QuickCarpet114/files/3693795/quickcarpet-2.0.0-dev.20191005.234048.zip) version? (Need to unzip it, for some reason GitHub doesn't allow JARs as attachments)

**Comment by keikoutou** [comment]
I didn't realize that there was already a problem in the past.

As a result, the same error.

Since it is impossible to reproduce the bug, introduce a directory on your computer.

[Please look.](https://drive.google.com/drive/folders/1nzOnXfXFjvBwX2OzVbz_9INEM1g3oDg7)

**Comment by skyrising** [comment]
At the moment 1.14.4 is unsupported. I'll try to release a stable version for 1.14.4, but updating to 1.15.1 is recommended.
